services:
  mermaid-agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: mermaid.env
    ports:
      - 7071:7070
    depends_on:
      - download-chat-model

  golang-agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: golang.env
    ports:
      - 7072:7070
    depends_on:
      - download-dev-model

  download-chat-model:
    provider:
      type: model
      options:
        model: ai/qwen2.5:latest

  download-dev-model:
    provider:
      type: model
      options:
        #model: k33g/qwen2.5-coder:3b-instruct-fp16
        model: ai/qwen2.5:latest
