
include:
  - ./mermaid-agent.yml
  - ./golang-agent.yml

services:

  download-chat-model:
    provider:
      type: model
      options:
        model: ai/qwen2.5:latest

  download-dev-model:
    provider:
      type: model
      options:
        model: k33g/qwen2.5-coder:3b-instruct-fp16
        #model: ai/qwen2.5:latest
